# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD$

PORTNAME=	django-tinymce
PORTVERSION=	2.0.4
PORTREVISION=	2
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	Django application to use TinyMCE editor

LICENSE=	MIT

NO_ARCH=	yes

USES=		python django zip
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
