# Created by: Sofian Brabez <sbrabez@gmail.com>
# $FreeBSD$

PORTNAME=	django-formtools
PORTVERSION=	2.1
PORTREVISION=	1
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Bootstrap forms for django

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist django

.include <bsd.port.mk>
