# Created by: Martin Wilke <miwi@FreeBSD.org>
# $FreeBSD$

PORTNAME=	django-classy-tags
PORTVERSION=	0.8.0
PORTREVISION=	1
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Class based template tags for Django

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils django

.include <bsd.port.mk>
