# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD$

PORTNAME=	recaptcha
PORTVERSION=	1.1.0
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}
DISTNAME=	django-${PORTNAME}-${PORTVERSION}

MAINTAINER=	tj@FreeBSD.org
COMMENT=	Django reCAPTCHA form field/widget integration app

USES=		python django
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
