# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD$

PORTNAME=	recaptcha
PORTVERSION=	2.0.2
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}
DISTNAME=	django-${PORTNAME}-${PORTVERSION}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Django reCAPTCHA form field/widget integration app

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils autoplist django

NO_ARCH=	yes

.include <bsd.port.mk>
