# $FreeBSD$

PORTNAME=	django-common-helpers
PORTVERSION=	0.9.2
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	kai@FreeBSD.org
COMMENT=	Common things every Django app needs

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils django

NO_ARCH=	yes

.include <bsd.port.mk>
