# Created by: Matthew X. Economou <xenophon+fbsdports@irtnog.org>
# $FreeBSD$

PORTNAME=	django-sekizai
PORTVERSION=	0.7
PORTREVISION=	3
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	xenophon+fbsdports@irtnog.org
COMMENT=	Block templating system for Django

RUN_DEPENDS=	${DJANGO_PKGNAMEPREFIX}django-classy-tags>=0.3.1:www/py-django-classy-tags@${DJANGO_FLAVOR}

USES=		python:2 django
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
