# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD$

PORTNAME=	configurations
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	GH
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	tj@FreeBSD.org
COMMENT=	Django project configuration using the composability of Python classes

USES=		python django
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes
USE_GITHUB=	yes
GH_ACCOUNT=	jazzband
GH_PROJECT=	django-configurations

.include <bsd.port.mk>
