# $FreeBSD$

PORTNAME=	django-storages
PORTVERSION=	1.9.1
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Generic storages for Django

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist django

.include <bsd.port.mk>
