# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD$

PORTNAME=	djangorestframework-filters
PORTVERSION=	0.10.2
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Filtering extension to Django REST Framework

LICENSE=	BSD2CLAUSE

USES=		python django
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
