# Created by: René Ladan <rene@freebsd.org>
# $FreeBSD$

PORTNAME=	django-overextends
PORTVERSION=	0.4.3
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	rene@FreeBSD.org
COMMENT=	Django reusable app enabling circular template inheritance

LICENSE=	BSD2CLAUSE

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}sphinx-me>=0.1.2:textproc/py-sphinx-me@${PY_FLAVOR}

NO_ARCH=	yes

USES=		python django
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
