# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD$

PORTNAME=	django-jsonfield
PORTVERSION=	1.0.3
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	GH
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	tj@FreeBSD.org
COMMENT=	Reusable JSONField model for Django to store ad-hoc data

USES=		python django
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes
USE_GITHUB=	yes
GH_ACCOUNT=	bradjasper

.include <bsd.port.mk>
