# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD$

PORTNAME=	jsonfield
PORTVERSION=	2.0.2
PORTREVISION=	1
CATEGORIES=	www python
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	ultima@FreeBSD.org
COMMENT=	Reusable JSONField model for Django to store ad-hoc data

LICENSE=	MIT
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	distutils autoplist django
NO_ARCH=	yes
USE_GITHUB=	yes
GH_ACCOUNT=	bradjasper

.include <bsd.port.mk>
