# $FreeBSD$

PORTNAME=	djangocms-admin-style
DISTVERSION=	1.4.0
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	kai@FreeBSD.org
COMMENT=	Pretty CSS styles for the django CMS admin interface

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist django

NO_ARCH=	yes

.include <bsd.port.mk>
