# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD$

PORTNAME=	django-countries
PORTVERSION=	5.3
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Provides country choices for use with django

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist django

.include <bsd.port.mk>
