# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD$

PORTNAME=	django-annoying
PORTVERSION=	0.10.4
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Eliminate annoying things in the Django framework

LICENSE=	BSD3CLAUSE

USES=		python django
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
