# Created by: Cheng-Lung Sung <clsung@FreeBSD.org>
# $FreeBSD$

PORTNAME=	django-annoying
PORTVERSION=	0.10.3
PORTREVISION=	1
DISTVERSIONPREFIX=	v
CATEGORIES=	www python
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Eliminate annoying things in the Django framework

LICENSE=	BSD3CLAUSE

USE_GITHUB=	yes

GH_ACCOUNT=	skorokithakis
USES=		python django
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
