# Created by: Kevin Golding <ports@caomhin.org>
# $FreeBSD$

PORTNAME=	django-registration
PORTVERSION=	2.1
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	ports@caomhin.org
COMMENT=	User-registration application for Django

LICENSE=	BSD3CLAUSE

USES=		python django
USE_PYTHON=	distutils autoplist

CONFLICTS_INSTALL=	pootle-[0-9]* py??-django*-django-registration-redux-[0-9]*

.include <bsd.port.mk>
