# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD$

PORTNAME=	swapper
PORTVERSION=	1.1.0
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Unofficial Django swappable models API

LICENSE=	MIT

NO_ARCH=	yes
USE_PYTHON=	autoplist concurrent distutils django
USES=		python

.include <bsd.port.mk>
