# $FreeBSD$

PORTNAME=	django-bulk-update
PORTVERSION=	2.2.0
PORTREVISION=	3
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	rene@FreeBSD.org
COMMENT=	Bulk update using a single query over Django ORM

LICENSE=	MIT

NO_ARCH=	yes
USES=		python:-3.4 django:111+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
