# Created by: Carlo Strub <cs@FreeBSD.org>
# $FreeBSD$

PORTNAME=	django-otp
PORTVERSION=	0.5.2
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Adding two-factor authentication to Django

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils django

.include <bsd.port.mk>
