# Created by: Carlo Strub <cs@FreeBSD.org>
# $FreeBSD$

PORTNAME=	django-otp
PORTVERSION=	0.4.2
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Adding two-factor authentication to Django

LICENSE=	BSD2CLAUSE

USES=		python django
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
