# Created by: John Hixson <john@ixsystems.com>
# $FreeBSD$

PORTNAME=	djangotoolbox
PORTVERSION=	1.6.1
PORTREVISION=	2
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	jhixson@gmail.com
COMMENT=	Common API for running Django on non-relational/NoSQL databases

LICENSE=	BSD3CLAUSE

USES=		python django
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
