# Created by: John Hixson <john@ixsystems.com>
# $FreeBSD$

PORTNAME=	djangotoolbox
PORTVERSION=	1.8.0
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	jhixson@FreeBSD.org
COMMENT=	Common API for running Django on non-relational/NoSQL databases

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist django

.include <bsd.port.mk>
