# Created by: Carlo Strub
# $FreeBSD$

PORTNAME=	django-simple-history
PORTVERSION=	1.8.2
PORTREVISION=	1
CATEGORIES=	www python
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	cs@FreeBSD.org
COMMENT=	Store model history and view/revert changes from admin site

LICENSE=	BSD3CLAUSE

USE_GITHUB=	yes

GH_ACCOUNT=	treyhunner
USES=		python django
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
