# Created by: Kevin Golding <ports@caomhin.org>
# $FreeBSD$

PORTNAME=	django_polymorphic
PORTVERSION=	0.9.2
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	ports@caomhin.org
COMMENT=	Seamless Polymorphic Inheritance for Django Models

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python django
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
