# Created by: Kubilay Kocak <koobs@FreeBSD.org>
# $FreeBSD$

PORTNAME=	django-mezzanine-grappelli
PORTVERSION=	0.4.5
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}
DISTNAME=	grappelli_safe-${PORTVERSION}

MAINTAINER=	koobs@FreeBSD.org
COMMENT=	Fork of django-grappelli for Mezzanine CMS

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

NO_ARCH=	yes

USES=		gettext python django
USE_PYTHON=	autoplist concurrent distutils

.include <bsd.port.mk>
