# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD$

PORTNAME=	djangorestframework
PORTVERSION=	3.6.4
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}
PKGNAMESUFFIX=	36

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Django REST framework

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist django=1.11

CONFLICTS_INSTALL=	${DJANGO_PKGNAMEPREFIX}djangorestframework

.include <bsd.port.mk>
