# $FreeBSD$

PORTNAME=	django-ranged-response
DISTVERSION=	0.2.0
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	kai@FreeBSD.org
COMMENT=	Modified Django FileResponse that adds Content-Range headers

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist django
NO_ARCH=	yes

.include <bsd.port.mk>
