# Created by: Ilya A. Arkhipov <rum1cro@yandex.ru>
# $FreeBSD$

PORTNAME=	django-subdomains
PORTVERSION=	2.1.0
PORTREVISION=	1
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	rum1cro@yandex.ru
COMMENT=	Subdomains helpers for the Django framework

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist django

.include <bsd.port.mk>
