# Created by: René Ladan <rene@freebsd.org>
# $FreeBSD$

PORTNAME=	django-transaction-hooks
PORTVERSION=	0.2
PORTREVISION=	2
CATEGORIES=	databases python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	rene@FreeBSD.org
COMMENT=	Django database backends to register transaction-commit hooks

LICENSE=	BSD3CLAUSE

NO_ARCH=	yes

USES=		python django
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
