# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD$

PORTNAME=	django-crispy-forms
PORTVERSION=	1.6.1
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	johannes@perceivon.net
COMMENT=	The best way to have Django DRY forms

LICENSE=	MIT

USES=		python django
USE_PYTHON=	distutils autoplist concurrent

.include <bsd.port.mk>
