# Created by: Kevin Golding <ports@caomhin.org>
# $FreeBSD$

PORTNAME=	django-keyedcache
PORTVERSION=	1.5.1
PORTREVISION=	2
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	ports@caomhin.org
COMMENT=	Simplified, speedy way to manage caching in Django apps

LICENSE=	BSD3CLAUSE

USES=		python django
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
