# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD$

PORTNAME=	django-bootstrap-form
PORTVERSION=	3.4
PORTREVISION=	1
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Bootstrap forms for django

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist django

.include <bsd.port.mk>
