# Created by: Alfred Perlstein <alfred@freebsd.org>
# $FreeBSD$

PORTNAME=	django-bootstrap-form
PORTVERSION=	3.3
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	alfred@FreeBSD.org
COMMENT=	Bootstrap forms for django

LICENSE=	MIT

USES=		python django
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
