# Created by: Tom Judge <tj@FreeBSD.org>
# $FreeBSD$

PORTNAME=	templatetag-sugar
PORTVERSION=	1.0
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}
DISTNAME=	django-${PORTNAME}-${PORTVERSION}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Library to make writing templatetags in Django sweet

USES=		python django
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
