# Created by: Johannes Meixner <johannes@perceivon.net>
# $FreeBSD$

PORTNAME=	paging
PORTVERSION=	0.2.5
PORTREVISION=	1
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}
DISTNAME=	django-${PORTNAME}-${PORTVERSION}

MAINTAINER=	python@FreeBSD.org
COMMENT=	Paging module for Django

# FIXME syntax error in __init__.py on Python 3.6
USES=		python:2.7 django
USE_PYTHON=	distutils autoplist
NO_ARCH=	yes

.include <bsd.port.mk>
