# Created by: Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD$

PORTNAME=	django-modern-rpc
PORTVERSION=	0.12.0
CATEGORIES=	www python django
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	sunpoet@FreeBSD.org
COMMENT=	Simple and modern JSON-RPC and XML-RPC server implementation for Django

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist concurrent distutils django

NO_ARCH=	yes

.include <bsd.port.mk>
