# Created by: John Hixson <john@ixsystems.com>
# $FreeBSD$

PORTNAME=	django-json-rpc
PORTVERSION=	0.6.2
PORTREVISION=	4
CATEGORIES=	www python
MASTER_SITES=	http://wiki.pcbsd.org/ports/
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	jhixson@gmail.com
COMMENT=	Simple JSON-RPC implementation for Django

LICENSE=	MIT

USES=		python django tar:bzip2
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
