# $FreeBSD$

PORTNAME=	django-cors-headers
PORTVERSION=	2.4.0
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	swills@FreeBSD.org
COMMENT=	Handles server headers required for Cross-Origin Resource Sharing

LICENSE=	MIT

USES=		python django
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
