# Created by: Kozlov Sergey <kozlov.sergey.404@gmail.com>
# $FreeBSD$

PORTNAME=	django-registration-defaults
PORTVERSION=	0.4.4
PORTREVISION=	2
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${DJANGO_PKGNAMEPREFIX}

MAINTAINER=	kozlov.sergey.404@gmail.com
COMMENT=	Default templates and settings for django-registration

LICENSE=	MIT

RUN_DEPENDS=	${DJANGO_PKGNAMEPREFIX}django-registration>=0:www/py-django-registration@${DJANGO_FLAVOR}

USES=		python django
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
